App\Entity\Image:
    properties:
        file:
            - Image:
                  mimeTypesMessage: L'image n'est pas au bon format ({{ type }}). Les formats autorisés sont {{ types }}.
                  disallowEmptyMessage: Le fichier est vide.
        alt:
            - NotBlank:
                  message: La description de l'image ne doit pas être vide.