App\Entity\Image:
    properties:
        file:
            - NotBlank:
                    message: Le champ image ne doit pas être vide.
            - Image:
                  mimeTypesMessage: L'image n'est pas au bon format ({{ type }}). Les formats autorisés sont {{ types }}.
                  disallowEmptyMessage: Le fichier est vide.