App\Domain\Entity\Picture:
    properties:
        file:
            - Image:
                  mimeTypesMessage: L'image n'est pas au bon format ({{ type }}). Les formats autorisés sont {{ types }}.
                  disallowEmptyMessage: Le fichier est vide.
                  groups: [registration, update_account]