App\Domain\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [email]
              message: Cette adresse email est déjà enregistrée.
              groups: [registration]
    properties:
        email:
            - NotBlank:
                  message: L'adresse email ne doit pas être vide.
                  groups: [registration]
            - Email:
                  message: L'adresse email {{ value }} n'est pas valide.
                  groups: [registration]
        username:
            - NotBlank:
                  message: Le pseudo ne doit pas être vide.
                  groups: [registration, update_account]
            - Length:
                  min: 2
                  max: 10
                  minMessage: 'Votre pseudo doit au minimum avoir {{ limit }} caractères'
                  maxMessage: 'Votre pseudo ne doit pas dépasser {{ limit }} caractères'
                  groups: [registration, update_account]
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
                  groups: [registration, update_account]
        password:
            - NotBlank:
                  message: Le mot de passe ne doit pas être vide.
                  groups: [registration, reset_password]
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
                  groups: [registration, reset_password]
        picture:
            - Valid: ~