App\DTO\CreateTrickDTO:
    properties:
        title:
            - NotBlank:
                  message: Le titre de la figure ne doit pas être vide.
            - Length:
                  min: 3
                  max: 30
                  minMessage: 'Le titre doit avoir au minimum {{ limit }} caractères.'
                  maxMessage: 'Le titre doit avoir au maxiumum {{ limit }} caractères.'
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
        description:
            - NotBlank:
                  message: La description de la figure ne doit pas être vide.
            - Length:
                  min: 3
                  max: 255
                  minMessage: 'La description doit avoir au minimum {{ limit }} caractères.'
                  maxMessage: 'La description doit avoir au maxiumum {{ limit }} caractères.'
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
        videos:
            - Valid: ~
        user:
            - Valid: ~
        category:
            - Valid: ~