App\DTO\UserRegistrationDTO:
    properties:
        email:
            - NotBlank:
                  message: L'adresse email ne doit pas être vide.
            - Email:
                  message: L'adresse email {{ value }} n'est pas valide.
        username:
            - NotBlank:
                  message: Le pseudo ne doit pas être vide.
            - Length:
                  min: 2
                  max: 10
                  minMessage: 'Votre pseudo doit au minimum avoir {{ limit }} caractères'
                  maxMessage: 'Votre pseudo ne doit pas dépasser {{ limit }} caractères'
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
        password:
            - NotBlank:
                  message: Le mot de passe ne doit pas être vide.
            - Type:
                  type: string
                  message: La valeur {{ value }} n'est pas valide.
        picture:
            - Valid: ~